# Generated by Django 2.2.4 on 2019-10-31 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='armario',
            name='laboratorio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='InvApp.Laboratorio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objeto',
            name='armario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='InvApp.Armario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objeto',
            name='conjunto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='InvApp.Conjunto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='conjuntos',
            field=models.ManyToManyField(to='InvApp.Conjunto'),
        ),
        migrations.AddField(
            model_name='registro',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='InvApp.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objeto',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='InvApp.Categoria'),
            preserve_default=False,
        ),
    ]
