# Generated by Django 2.2.4 on 2019-11-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0003_auto_20191108_1302'),
        ('InvApp', '0003_auto_20191108_1153'),
    ]

    operations = [
    ]
