# Generated by Django 2.2.6 on 2019-11-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0004_merge_20191108_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conjunto',
            name='stock',
        ),
        migrations.AddField(
            model_name='objeto',
            name='condicion',
            field=models.IntegerField(choices=[(1, 'Nuevo'), (2, 'Usado'), (3, 'Arreglar'), (4, 'Roto')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objeto',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Prestado'), (2, 'Disponible'), (3, 'En mantenimiento')], default=1),
            preserve_default=False,
        ),
    ]
