# Generated by Django 2.2.6 on 2019-11-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0007_auto_20191114_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Disponible'), (2, 'Prestado'), (3, 'En mantenimiento')], default=1),
        ),
    ]
