# Generated by Django 2.2.7 on 2019-11-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0008_auto_20191114_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='conjuntos',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='usuario',
        ),
    ]
