# Generated by Django 2.2 on 2019-11-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0003_auto_20191114_1123'),
        ('InvApp', '0008_auto_20191114_1310'),
    ]

    operations = [
    ]
