# Generated by Django 2.2 on 2019-11-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0009_merge_20191115_1327'),
        ('InvApp', '0009_auto_20191115_1233'),
    ]

    operations = [
    ]
