# Generated by Django 2.2.7 on 2019-11-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0010_merge_20191115_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='usuario',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
