# Generated by Django 2.2.4 on 2019-12-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0011_registro_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name_plural': 'Especialidades'},
        ),
        migrations.RemoveField(
            model_name='armario',
            name='id_Colegio',
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='ubicacion',
            field=models.CharField(max_length=30),
        ),
    ]
