# Generated by Django 2.2.4 on 2019-12-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0013_auto_20191201_2112'),
        ('InvApp', '0013_auto_20191202_0225'),
    ]

    operations = [
    ]
